---
- name: Ensure user
  mysql_user:
    name: '{{ item.name }}'
    host: '{{ item.host | default(omit) }}'
    password: '{{ item.password | default(omit) }}'
    priv: '{{ item.priv | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
  with_items: '{{ mariadb_users | default([]) }}'
